config/routes.rb
Rails.application.routes.draw do
  # root route - home page
  root 'welcome#index'
  # landing page/ home page
  get 'welcome' => 'welcome#index'
  # devise user routes (signup, login, etc.)
  devise_for :users
  # nested user's movies routes
  resources :users, only: [:show] do
    resources :movies, only: [:index, :show, :create, :destroy], shallow: true do
      resources :reviews, only: [:create, :edit, :update, :destroy], shallow: true
    end
  end


  # search movies route
  get 'search' => 'movies#search' # search_path => /search
  # movie details route
  get 'details/:imdb_id' => 'movies#details', as: 'details' # details_path(:id) => /details/:id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_and_belongs_to_many :users
	has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :movies
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :find_movie, only: [:show, :destroy]

	def index
		@image_url = 'post-bg'
		user = User.find(params[:user_id])
		if current_user == user
			@movies = current_user.movies
		else
			flash[:alert] = "You do not have permission to access this page!"
			redirect_to root_path
		end
	end

	def search
		@image_url = 'about-bg'
		q = params[:q]
		@title = q
		# create end point from search query and API url
		url = "http://www.omdbapi.com/?s="
		end_point = url + q
		# make API call to end point, set result equal to response
		response = RestClient.get(end_point)
		# parse response.body and set result equal to data
		data = JSON.parse(response.body)
		@movies = data["Search"]
		if @movies
			render :search
		else
			flash[:alert] = "Sorry, your search came back empty, please try again."
			redirect_to root_path
		end
	end

	def details
		@movie = Movie.new
		imdb_id = params[:imdb_id]
		url = "http://www.omdbapi.com/?i="
		end_point = url + imdb_id + '&plot=full'

		response = RestClient.get(end_point)
		@movie_info = JSON.parse(response.body)
	end

	def create
		@movies = Movie.all
		if @movies.map(&:imdb_id).include?(movie_params[:imdb_id])
			@movie = Movie.find_by(imdb_id: movie_params[:imdb_id])
			@movie.users << current_user
			flash[:notice] = "#{@movie.title} successfully favorited."
			redirect_to @movie
		else
			@movie = current_user.movies.build(movie_params)
			if current_user.save
				flash[:notice] = "#{@movie.title} successfully favorited."
				redirect_to @movie
			else
				flash[:alert] = "Unable to favorite movie."
				redirect_to root_path
			end
		end
	end

	def show
		@review = Review.new
	end

	def destroy
		current_user.movies.delete(@movie)
		flash[:alert] = "Movie successfully deleted!"
		redirect_to user_movies_path(current_user)
	end

	private
		def find_movie
			@movie = Movie.find(params[:id])
		end

		def movie_params
			params.require(:movie).permit(:title, :year, :plot, :imdb_id)
		end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_review, only: [:edit, :update, :destroy]

  def create
  	@movie = Movie.find(params[:movie_id])
  	@review = @movie.reviews.build(review_params)
  	@review.user = current_user
  	if @movie.save
  		flash[:notice] = "Review added successfully."
  		redirect_to @movie
  	else
  		flash[:alert] = "Review could not be added, please try again."
  		redirect_to @movie
  	end
  end

  def edit
  	if @review.user != current_user
  		sign_out current_user
  		redirect_to root_path
  	end
  end

  def update
  	if @review.user == current_user
  		if @review.update(review_params)
  			flash[:notice] = "Review updated successfully."
  			redirect_to @review.movie
  		else
  			flash[:alert] = "Unable to update review."
  			render :edit
  		end
  	else
  		sign_out current_user
  		redirect_to root_path
  	end

  end

  def destroy
  	@movie = @review.movie
  	if @review.user == current_user
  		@review.destroy
  		flash[:alert] = "Review deleted successfully."
  		redirect_to @movie
  	else
  		sign_out current_user
  		redirect_to root_path
  	end
  end

  private
  	def find_review
  		@review = Review.find(params[:id])
  	end

  	def review_params
  		params.require(:review).permit(:body)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<ul class="list-inline text-center">
					<li>
						<a href="#">
							<span class="fa-stack fa-lg">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
					<li>
						<a href="#">
							<span class="fa-stack fa-lg">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
					<li>
						<a href="#">
							<span class="fa-stack fa-lg">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-github fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
				</ul>
				<p class="copyright text-muted">Copyright &copy; Movie App 2016</p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
	<div class="container">
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				Menu <i class="fa fa-bars"></i>
			</button>
			<%= link_to 'IMDB App', root_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<% if user_signed_in? %>
				<li><%= link_to 'My Movies', user_movies_path(current_user) %></li>
				<% end %>
				<% if user_signed_in? %>
				<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				<% else %>
				<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
				<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/img/<%= @image_url || 'home-bg' %>.jpg')">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
				<h1><%= @title || 'Movie App' %></h1>
					<hr class="small">
					<span class="subheading">Review your favorite movie today!</span>
				</div>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_notices.html.erb
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Movie App</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= render 'layouts/notices' %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_tag(search_path, method: "get") do %>
	<div class="row control-group">
		<div class="form-group col-xs-12 floating-label-form-group controls">
			<%= label_tag(:q, "Search for:") %>
			<%= text_field_tag :q, nil, class: 'form-control', placeholder: 'Search for...' %>
		</div>
		&nbsp;
		<div class="row">
			<div class="form-group col-xs-12">
				<%= submit_tag("Search", class: 'btn btn-sm btn-default') %>
			</div>
		</div>
	</div>
<% end %>

app/views/movies/details.html.erb
<h1><%= @movie_info["Title"] %></h1>
<p>Year: <%= @movie_info["Year"] %></p>
<p><%= @movie_info["Plot"] %></p>
<% if !current_user.movies.map(&:imdb_id).include?(@movie_info["imdbID"]) %>
<%= simple_form_for([current_user, @movie]) do |f| %>
	<%= f.hidden_field :title, :value => @movie_info["Title"] %>
	<%= f.hidden_field :year, :value => @movie_info["Year"] %>
	<%= f.hidden_field :plot, :value => @movie_info["Plot"] %>
	<%= f.hidden_field :imdb_id, :value => @movie_info["imdbID"] %>
	<%= f.button :submit, 'Favorite', class: 'btn btn-primary' %>
<% end %>
<% end %>
<%= link_to 'Back', :back %>

app/views/movies/index.html.erb
<div class="row">
	<div class="col-md-8">
		<h1>My Favorite Movies</h1>
		<% if @movies.length > 0 %>
		<% @movies.each do |movie| %>
			<%= link_to movie.title, movie %> | <%= link_to 'Delete', movie, method: :delete, data: {confirm: 'Are you sure?'}, class: 'delete' %>
			<hr>
		<% end %>
		<% else %>
			<p>You don't have any favorites yet!</p>
			<p>Search for a movie now:</p>
		<% end %>
	</div>
	<div class="col-md-4">
		<h1>Search:</h1>
		<%= render 'form' %>
	</div>
</div>
<%= link_to 'Back', :back %>

app/views/movies/search.html.erb
<div class="row">
	<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 text-center">
		<%= render 'form' %>
		<% @movies.each do |movie| %>
		<div class="post-preview">
			<h2 class="post-title">
				<%= movie["Title"] %>
			</h2>
			<p class="post-subtitle">
				Year: <%= movie["Year"] %>
			</p>
			<p class="post-meta"><%= link_to 'Details', details_path(movie["imdbID"]) %></p>
		</div>
		<hr>
		<% end %>
	</div>
</div>

app/views/movies/show.html.erb
<div class="row">
		<div class="col-md-8">
			<h1><%= @movie.title %></h1>
			<p><strong>Year</strong>: <%= @movie.year %></p>
			<p><strong>Plot</strong>: <%= @movie.plot %></p>
			<% if !@movie.reviews.map(&:user_id).include?(current_user.id) %>
			<%= render 'reviews/form' %>
			<% end %>
			<%= link_to 'Back', :back %> | <%= link_to 'Favorites', user_movies_path(current_user) %>
		</div>
		<div class="col-md-4">
			<h1>Reviews:</h1>
			<% @movie.reviews.each do |review| %>
				<% if review.user == current_user %>
				<%= link_to edit_review_path review do %>
					<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
				<% end %>
				<%= link_to review, method: :delete, data: { confirm: 'Are you sure?' } do %>
					<i class="fa fa-trash" aria-hidden="true"></i>
				<% end %>	
				<% end %>
				<strong><%= review.user.email %></strong>: <%= review.body %>
				<hr>
			<% end %>
		</div>
</div>

app/views/reviews/_form.html.erb
<h1>Add Review:</h1>
<%= simple_form_for([@movie, @review], html: { class: 'form-inline' }) do |f| %>
  <p>
    <%= f.input :body, label: false %>
  </p>
  <p>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= render 'form' %>

app/views/welcome/index.html.erb
<h1>Welcome <%= current_user.email %>, search for a movie!</h1>

<%= render 'movies/form' %>